version: '3.8'

services:
  nginx:
    container_name: 'gather-pets-nginx'
    image: nginx:stable
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    image: node:latest
    container_name: gather-pets-api
    restart: always
    volumes:
      - ~/gather-pets-project/application/gather-pets-api:/usr/src/app
    working_dir: /usr/src/app
    # exec for PROD
    #command: yarn start
    command: yarn dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
      
  db:
    container_name: 'gather-pets-db'
    image: mysql:latest
    restart: always
    volumes:
      - ~/gather-pets-project/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"


networks:
  default:
    external:
      name: gather-pets-network