version: "3.8"

services:
  nginx:
    container_name: "gather-pets-nginx"
    image: nginx:stable
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    build: .
    entrypoint: .docker/install
    container_name: gather-pets-api
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - /Volumes/kanu/Developer/MyProjects/application/gather-pets-api:/home/node/app

  db:
    container_name: "gather-pets-db"
    image: mysql:5.7.33
    restart: always
    volumes:
      - /Volumes/kanu/Developer/MyProjects/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

networks:
  default:
    external:
      name: gather-pets-network
