version: '3.8'

services:
  nginx:
    container_name: 'gather-pets-nginx'
    image: nginx:stable
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    image: node:latest
    container_name: gather-pets-api
    restart: always
    volumes:
      - ~/gather-pets-project/application/gather-pets-api:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
      
networks:
  default:
    external:
      name: gather-pets-network